### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by louich**
Out dated revision `github.com/Mongey/ksql@7f949ab529b9871d39185c6705f543a21fe25eba`

When installing package with go modules, `go install` throws:

```shell
go: converting Gopkg.lock: stat github.com/Mongey/ksql@7f949ab529b9871d39185c6705f543a21fe25eba: unknown revision 7f949ab529b9871d39185c6705f543a21fe25eba
```

### CODE REVIEW

**Comment by Mongey** [comment]
Thanks @louich ! Sorry that you ran into issues. I pushed some extra commits to fixup CI + fully move over to go modules. Hopefully that works 🙏

**Comment by louich** [comment]
Yeah :ok_hand: excellent job. Thanks for your responsiveness, it seems to build fine. Will you merge it soon?

**Comment by louich** [comment]
Many thanks :tada:

**Comment by Mongey** [comment]
np! :shipit:  :shipit:  :shipit:  :shipit: 

Hopefully it works 😅 It's been quite a while since I've used KSQL / this provider. Raise some issues if you run into anything and I can take a look 👀

**Pull request merged**
